import { Metadata } from 'next'


export const metadata: Metadata = {
    title: 'LISTINHA',
    description: 'Generated by create next app',
    icons: {
        icon: "/logos/logo.png"
    }
}

export default function ListaLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main>
            {children}
            <p className='text-center'>listenha</p>
        </main>
    )
}
